services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: on-failure
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - dockin
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    restart: on-failure
    env_file: .env
    volumes:
      - wp:/var/html/wordpress
    networks:
      - dockin
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - wp:/var/html/wordpress
    networks:
      - dockin

volumes:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/luntiet/data/db
  wp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/luntiet/data/wp

networks: 
  dockin:
    driver: bridge
