services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - /var/db:/var/db
    networks:
      - dockin
  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - dockin
  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - /var/html:/var/html
    networks:
      - dockin
networks: 
  dockin:
    driver: bridge
